### ISSUE TITLE
ERROR:  extension "pg_net" has no installation script nor update path for version "0.7.3" 

### ISSUE THREAD

**Issue by digoal** [supabase/pg_net#111]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
```
create extension pg_net;
```
## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context
```
# cd pg_net/sql
# cp -f -n ./pg_net.sql ./pg_net--0.7.3.sql /usr/share/postgresql/14/extension/
```

**Comment by steve-chavez** [comment]
@digoal Please share the steps you followed to run into this error.

Was it a `make && make install`? https://github.com/supabase/pg_net#configuring-your-deviceserver

**Comment by steve-chavez** [comment]
> cd pg_net/sql
> cp -f -n ./pg_net.sql ./pg_net--0.7.3.sql /usr/share/postgresql/14/extension/

Ah, I think I get it. You're not using `make` to install the extension. 

When you run `make` it will generate `pg_net--0.7.3.sql`, thus clear the error you're seeing. This is defined here:

https://github.com/supabase/pg_net/blob/master/Makefile#L15-L16
