### ISSUE TITLE
"SSL connect error", "Error in the HTTP2 framing layer" while using edge functions

### ISSUE THREAD

**Issue by steve-chavez** [supabase/pg_net#115]
## Problem

A customer has reported "SSL connect error", "Error in the HTTP2 framing layer" showing in the `pg_net._http_response` table while making calls to Supabase edge functions. The customer informs this happens after 270 requests. 

This seems to be related to `libcurl`:

- https://github.com/curl/curl/issues/3750
- https://github.com/curl/curl/issues/10634. According to https://github.com/curl/curl/commit/cbe9d82c22c38753ad6372e5040e4c51b3695dc7, this fix is available on curl 8.0.0. While the Supabase platform has `curl 7.68.0`.

## Proposal

Vendor `libcurl`, this way we get the latest fixes and we're not dependent on the Supabase platform version.

**Comment by metarama** [comment]
When are we going to upgrade to using curl version 8?

I am using the hosted version of Supabase. I can easily reproduce this error... just do GET calls that return JSON bodies. I do about 500 calls within couple of minutes and I see these SSL errors.

**Comment by metarama** [comment]
Abandoned pg_net. Using http extension.

**Comment by steve-chavez** [comment]
>  The result has no mention of the curl version.

We used to have that at one point https://github.com/supabase/pg_net/pull/122. Maybe we can bring it back.

Now that we have a Nix build we might be able to fix this issue too.

**Comment by steve-chavez** [comment]
This should no longer happen now that Supabase cloud has libcurl 8.6.0.

Please reopen if the error happens again.

**Comment by harshgour** [comment]
@steve-chavez we are facing the same issue, a lot of POST requests are going into these errors.

**Comment by steve-chavez** [comment]
@harshgour Which version of pg_net are you using? Check with:

```
select extversion from pg_extension where extname = 'pg_net';
```

The latest version is `0.10.0`

**Comment by marcelorl** [comment]
how can I get pg_net upgraded to 0.11.0 (latest version)? 

I have already upgraded postgres through supabase
Have tried the commands:

ALTER EXTENSION pg_net UPDATE; - it does not fail, but it does not upgrade the version
ALTER EXTENSION pg_net UPDATE TO '0.11.0'; - it errors with: `ERROR:  22023: extension "pg_net" has no update path from version "0.8.0" to version "0.11.0"`

Tried on both my remote and local environment.

Any idea?

**Comment by TheOtherBrian1** [comment]
@marcelorl, unfortunately, pg_net v0.11 has not yet been added to the available Supabase images. The newest Supabase Postgres image is pending approval from the Infra Team.

**Comment by TheOtherBrian1** [comment]
@marcelorl, have you created a [ticket](https://supabase.com/dashboard/support/new)? I'm suspicious if there may be a secondary factor, such as memory strain

**Comment by marcelorl** [comment]
@TheOtherBrian1 it actually doesnt necessarily need to be 0.11.0.
I tried even version 0.10.0 with: `ALTER EXTENSION pg_net UPDATE TO '0.10.0';` I get the error:

**Comment by steve-chavez** [comment]
@marcelorl You can upgrade by going to https://supabase.com/dashboard/project/_/settings/infrastructure, there's a button there.

**Comment by steve-chavez** [comment]
`0.13.0` is the latest version, see https://github.com/supabase/pg_net/issues/86#issuecomment-2471290734 for how to upgrade

**Comment by steve-chavez** [comment]
Is it self hosted or cloud? What endpoint are you hitting?

**Comment by steve-chavez** [comment]
> ngrok (tunneling to my localhost).

Hm, that is not a setup apt for production. Do all requests fail or just some? If it's just some, then that would mean there's nothing wrong with pg_net itself, ngrok is probably terminating the connection with rate limiting.
