### ISSUE TITLE
>1024 concurrent requests crashes background worker

### ISSUE THREAD

**Issue by olirice** [supabase/pg_net#12]
When a large number of requests starts at the same time (> 1024) the worker crashes

Run a webserver locally:

Process 1
```
python3 -m http.server
```
SQL
```sql
create extension pg_net;
select net.http_get('http://0.0.0.0:8000') from generate_series(1,5000);
```

Error
```
postgres=# 2021-07-23 16:20:16.307 CDT [32736] ERROR:  CURL error code: 56 
```

**Comment by olirice** [comment]
resolved

**Comment by steve-chavez** [comment]
@olirice This was fixed in https://github.com/supabase/pg_net/pull/15 right? I assume there's now an error in the response table instead of the worker dying.

**Comment by olirice** [comment]
yep, that's right
