### ISSUE TITLE
0.10.0 build failure

### ISSUE THREAD

**Issue by devrimgunduz** [supabase/pg_net#143]
0.10.0 fails to build against GCC 11, GCC 8.5.0 and GCC 7.5.0 (RHEL 9 , RHEL 8 and SLES 15 respectively). Can you please take a look? Thanks!

> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2   -DEXTVERSION=\"0.10.0\" -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o src/util.bc src/util.c
src/worker.c:277:19: error: call to undeclared function 'curl_easy_nextheader'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  277 |   while((header = curl_easy_nextheader(ez_handle, CURLH_HEADER, 0, prev))) {
      |                   ^
src/worker.c:277:51: error: use of undeclared identifier 'CURLH_HEADER'; did you mean 'CURLOPT_HEADER'?
  277 |   while((header = curl_easy_nextheader(ez_handle, CURLH_HEADER, 0, prev))) {
      |                                                   ^~~~~~~~~~~~
      |                                                   CURLOPT_HEADER
/usr/include/curl/curl.h:1205:11: note: 'CURLOPT_HEADER' declared here
 1205 |   CURLOPT(CURLOPT_HEADER, CURLOPTTYPE_LONG, 42),
      |           ^
src/worker.c:278:76: error: incomplete definition of type 'struct curl_header'
  278 |     JsonbValue key   = {.type = jbvString, .val = {.string = {.val = header->name,  .len = strlen(header->name)}}};
      |                                                                      ~~~~~~^
src/worker.c:272:10: note: forward declaration of 'struct curl_header'
  272 |   struct curl_header *header, *prev = NULL;
      |          ^
src/worker.c:278:105: error: incomplete definition of type 'struct curl_header'
  278 |     JsonbValue key   = {.type = jbvString, .val = {.string = {.val = header->name,  .len = strlen(header->name)}}};
      |                                                                                                   ~~~~~~^
src/worker.c:272:10: note: forward declaration of 'struct curl_header'
  272 |   struct curl_header *header, *prev = NULL;
      |          ^
src/worker.c:279:76: error: incomplete definition of type 'struct curl_header'
  279 |     JsonbValue value = {.type = jbvString, .val = {.string = {.val = header->value, .len = strlen(header->value)}}};
      |                                                                      ~~~~~~^
src/worker.c:272:10: note: forward declaration of 'struct curl_header'
  272 |   struct curl_header *header, *prev = NULL;
      |          ^
src/worker.c:279:105: error: incomplete definition of type 'struct curl_header'
  279 |     JsonbValue value = {.type = jbvString, .val = {.string = {.val = header->value, .len = strlen(header->value)}}};
      |                                                                                                   ~~~~~~^
src/worker.c:272:10: note: forward declaration of 'struct curl_header'
  272 |   struct curl_header *header, *prev = NULL;
      |          ^
6 errors generated.
make[1]: *** [/usr/pgsql-16/lib/pgxs/src/makefiles/../../src/Makefile.global:1093: src/worker.bc] Error 1
make[1]: *** Waiting for unfinished jobs....
src/worker.c: In function 'jsonb_headers_from_curl_handle':
src/worker.c:277:19: error: implicit declaration of function 'curl_easy_nextheader'; did you mean 'curl_easy_strerror'? [-Werror=implicit-function-declaration]
  277 |   while((header = curl_easy_nextheader(ez_handle, CURLH_HEADER, 0, prev))) {
      |                   ^~~~~~~~~~~~~~~~~~~~
      |                   curl_easy_strerror
src/worker.c:277:51: error: 'CURLH_HEADER' undeclared (first use in this function); did you mean 'CURLOPT_HEADER'?
  277 |   while((header = curl_easy_nextheader(ez_handle, CURLH_HEADER, 0, prev))) {
      |                                                   ^~~~~~~~~~~~
      |                                                   CURLOPT_HEADER
src/worker.c:277:51: note: each undeclared identifier is reported only once for each function it appears in
src/worker.c:278:76: error: invalid use of undefined type 'struct curl_header'
  278 |     JsonbValue key   = {.type = jbvString, .val = {.string = {.val = header->name,  .len = strlen(header->name)}}};
      |                                                                            ^~
src/worker.c:278:105: error: invalid use of undefined type 'struct curl_header'
  278 |     JsonbValue key   = {.type = jbvString, .val = {.string = {.val = header->name,  .len = strlen(header->name)}}};
      |                                                                                                         ^~
src/worker.c:279:76: error: invalid use of undefined type 'struct curl_header'
  279 |     JsonbValue value = {.type = jbvString, .val = {.string = {.val = header->value, .len = strlen(header->value)}}};
      |                                                                            ^~
src/worker.c:279:105: error: invalid use of undefined type 'struct curl_header'
  279 |     JsonbValue value = {.type = jbvString, .val = {.string = {.val = header->value, .len = strlen(header->value)}}};
      |

**Comment by steve-chavez** [comment]
> src/worker.c:277:19: error: call to undeclared function 'curl_easy_nextheader'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

Looks like this is because you're linking against an older libcurl version. Recently we change the requirement to:

 ```
libcurl >= 7.83.
``` 

It's mentioned at the top [here](https://github.com/supabase/pg_net?tab=readme-ov-file#pg_net).

**Comment by steve-chavez** [comment]
I'll add a static assertion for the `libcurl` version to ensure the error is clear.

**Comment by steve-chavez** [comment]
Closing as now a lower libcurl version should show a clear compile error.

```
src/worker.c:31:1: error: static assertion failed: "libcurl >= 7.83.0 is required"
```

Let me know if you're able to do the build on RHEL/SLES.

**Comment by devrimgunduz** [comment]
Thanks a lot. Removed this package from RHEL 9 and 8 as they don't provide libcurl >= 7.83.
