### ISSUE TITLE
 trigger on net._http_response, which modifies data in another table, does not trigger Realtime update

### ISSUE THREAD

**Issue by scholz-timo** [supabase/pg_net#152]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

 trigger on net._http_response, which modifies data in another table, does not trigger Realtime update

## To Reproduce

- create a trigger on net._http_response which insert received data into another table
- have realtime enabled on the table with the inserted data
- make an api call using net.http_get
- wait for realtime event (no realtime event gets called in time (maybe a [apply_rls call](https://github.com/supabase/realtime/blob/07a0a1500205c6698994381607064efe0d6ea270/lib/realtime/tenants/repo/migrations/20230128025212_enable_filtering_on_delete_record.ex#L8) is missing for [StartTransactionCommand](https://github.com/supabase/pg_net/blob/master/src/worker.c#L387) and [CommitTransactionCommand](https://github.com/supabase/pg_net/blob/master/src/worker.c#L387))
- after 10-30 sec a event is received, prob via fallback realtime sync

```sql

create table uuids(uuid uuid not null default gen_random_uuid());

CREATE FUNCTION do_insert_uuid() RETURNS trigger LANGUAGE plpgsql as $$ BEGIN

INSERT INTO uuids(uuid) VALUES (DEFAULT);

END;
$$;

CREATE TRIGGER insertUUID
AFTER INSERT ON uuids FOR EACH ROW
EXECUTE function do_insert_uuid ();

alter publication supabase_realtime
add table uuids;

``` 

## Expected behavior

Update should happen faster.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

## Additional context

Additional performance hits could be mitigated by using a feature flag for the suggested changes.

**Comment by scholz-timo** [comment]
Of course, there is a postgresql replication_slot missing.
Only CommitTransactionCommand should have the apply_rls_call().

Optimally there should be a seperation between async and sync requests, maybe extend the request table with an flag if fast updates should be enabled.

**Comment by olirice** [comment]
A small delay between when you call `net.http_get` and get a realtime update is expected. The background worker that makes HTTP requests polls with a 1 second interval, the HTTP endpoint could be sluggish, and realtime also polls for changes

The background worker and realtime poller shouldn't account for > 3-5 second though, so if you're seeing 30 seconds thats likely caused by resource contention on the database, a slow response from the HTTP server, or something like that

---

Could you please take another look at the reproducible example from your first message? pg_net is not referenced

A complete copy/paste reproducible example of the issue you're facing will help us a lot in debugging

**Comment by steve-chavez** [comment]
> create a trigger on net._http_response which insert received data into another table

Is not recommended to do that, the `net` tables shouldn't be modified. Insertions to the response table should be as fast as possible. (this could change once https://github.com/supabase/pg_net/issues/62 is done).

https://github.com/supabase/pg_net/pull/139 also improves speed, I suggest you try again once a new version of pg_net is released.

**Comment by steve-chavez** [comment]
>  I suggest you try again once a new version of pg_net is released.

new version already released https://github.com/supabase/pg_net/releases/tag/v0.11.0
