### ISSUE TITLE
restart background worker on crash

### ISSUE THREAD

**Issue by olirice** [supabase/pg_net#24]

**Comment by steve-chavez** [comment]
@olirice How did you manage to crash it? I thought https://github.com/supabase/pg_net/pull/15 fixed these cases.

**Comment by olirice** [comment]
Yeah it did. That solved the ones that showed up in the test suite. If you're confident that the background worker is crash-proof we can skip this but it'd be nice to have a second line of defense against the worker failing b/c monitoring for craashes would be difficult.
