### ISSUE TITLE
Remove `strict` modifier on functions

### ISSUE THREAD

**Issue by soedirgo** [supabase/pg_net#25]
https://github.com/supabase/pg_net/pull/17#issuecomment-887988208

**Comment by steve-chavez** [comment]
The referenced issue talks mostly in terms of `STRICT` not being [inlinable](https://wiki.postgresql.org/wiki/Inlining_of_SQL_functions).

https://stackoverflow.com/questions/8455177/function-executes-faster-without-strict-modifier

Really this only matters when using set returning functions and our `http_get/post` are scalars. So it's not necessary to make this change.
