### ISSUE TITLE
pg_net and http exts have the same http_method domain

### ISSUE THREAD

**Issue by w3b6x9** [supabase/pg_net#28]
# Bug report

## Describe the bug

If a user already has `http` extension on their database and wants to create `pg_net` extension, or vice versa, then they will get _type "http_method" already exists_ error.

## To Reproduce

1. `create extension http;`
2. `create extension pg_net;`
4. See error: _type "http_method" already exists_

## System information

- Version of Postgres: 12.5

**Comment by olirice** [comment]
looks like `http_method` domain is being created outside the `net` schema in `pg_net`

**Comment by olirice** [comment]
resolved by 8acb39c1a06d47c8a987bf1763ce949014cb5135
