### ISSUE TITLE
Use `curl_multi_socket_action` with libevent instead of `curl_multi_perform`

### ISSUE THREAD

**Issue by soedirgo** [supabase/pg_net#46]
Differences laid out here: https://curl.se/libcurl/c/libcurl-multi.html.

Could potentially help with https://github.com/supabase/pg_net/issues/13.

**Comment by steve-chavez** [comment]
The pg background worker module already has some functions that encapsulate kqueue, select, poll([ref](https://github.com/postgres/postgres/blob/master/src/backend/storage/ipc/latch.c#L40-L48)). Maybe we should try to use that first.

**Comment by steve-chavez** [comment]
> Hmm not too familiar with postgres internals, but that looks like a purpose-built latch implementation for the storage manager.

Been learning postgres internals on my own, so I'm not sure either. I just got a hunch from seeing pg_cron codebase(uses WaitLatch [here](https://github.com/citusdata/pg_cron/blob/main/src/pg_cron.c#L986-L996)) and that there are events for sockets [here](https://github.com/postgres/postgres/blob/master/src/include/storage/latch.h#L122-L127).
