### ISSUE TITLE
Allow http DELETE

### ISSUE THREAD

**Issue by psteinroe** [supabase/pg_net#63]
# Feature request

## Is your feature request related to a problem? Please describe.

We want to send a delete request to a serverless function within a Nextjs api to trigger the deletion of the entity at an external provider after it was deleted in our database.

## Describe the solution you'd like

Support http delete in addition to post and get.

## Describe alternatives you've considered

Adding another endpoint, e.g. /delete, and sending a post request there

**Comment by tvogel** [comment]
See also #77 . Lack of DELETE makes it impossible to use pg_net to clean up supabase storage objects in UPDATE/DELETE Postgres triggers. Or am I missing something?

**Comment by steve-chavez** [comment]
Can be used on v0.7 as:

```sql
        select net.http_delete(
            url:='https://httpbin.org/delete'
        ,   params:= '{"param-foo": "bar"}'
        ,   headers:= '{"X-Baz": "foo"}'
        );
```

This will be deployed to Supabase soon.

**Comment by GaryAustin1** [comment]
Is `body` also supported in delete?  I have a delete storage task that uses bulk delete with the http extension right now.  It uses body for pathnames.  I don't really need to wait for a response in what I'm doing and pg_net would be ideal.

**Comment by steve-chavez** [comment]
@GaryAustin1 Not supported, will track it on https://github.com/supabase/pg_net/issues/77
