### ISSUE TITLE
How does pg_net fit into the overall supabase architecture?

### ISSUE THREAD

**Issue by psteinroe** [supabase/pg_net#73]
Hey,

we are making quite heavy use of pg_net, mainly to make a request to an external api from within a trigger. For some of these, we will now migrate to a postgres-based queue (postgraphile-worker / pg-boss) to have better observability.

During the migration, I began to wonder how pg_net fits into the supabase architecture, for what use-cases it is supposed to be used and what its limitations are, especially regarding performance.

As an example, we are using segment to collect usage data and want to track events from within the database. One option would be to use pg_net to make a request to the Segment API. We created a simple segement.track function which makes the request using pg_net. When our usage grows, we might get a few events per seconds. How much requests is pg_net supposed to handle? As an alternative, we could either send the requests batch-wise or use a queueing solution and drop pg_net. Further, a webhook or queuing plugin for realtime would probably be a more scalable alternative. 

Is there any official guidance on the scalability and intend of pg_net?

Best
Philipp

**Comment by steve-chavez** [comment]
> How much requests is pg_net supposed to handle?

Right now it's configured at 200 requests per second, you can check this with `show pg_net.batch_size`.

`pg_net.batch_size` can be increased but doing so will make the `pg_net` worker have a higher CPU usage - we expect to reduce this with https://github.com/supabase/pg_net/issues/62.

> for what use-cases it is supposed to be used 
>  intend of pg_net?

It's used for webhooks. You can read more about the intend on https://supabase.com/blog/supabase-functions-updates#hooks-technical-design-pg_net-v01

**Comment by psteinroe** [comment]
Thanks for the reply!

> It's used for webhooks.

What is the reason for Webhooks still being in beta? 

Maybe we could add a few common usage examples in the docs? I encountered a few people already that were having problems with using pg_net, e.g. for sending a request from within a trigger. Doing as much as sending them [this gist](https://gist.github.com/psteinroe/121a8c2162f7fc6c8408339315033ab3) already helped. Common questions that should be answered in the docs:

- How many req/s can pg_net handle?
- Linking or copying parts of the blog post about Webhooks
- How to use the authorisation of the current user in the request?
- How to use pg_net from within a trigger? 

I think this would help people a lot.

**Comment by steve-chavez** [comment]
> What is the reason for Webhooks still being in beta?

Once `pg_net` hits 1.0, Webhooks should be stable. For this we'd need to close https://github.com/supabase/pg_net/issues/62 and https://github.com/supabase/pg_net/issues/49.

Development on pg_net stagnated for a while but since https://github.com/supabase/pg_net/pull/68 (a revert of a previous change) we're able to pick up dev again. So I expect pg_net to hit 1.0 for next launch week tops.

> Maybe we could add a few common usage examples in the docs?

Absolutely, thanks for the suggestions. The interface will change a bit when #62 is done so I'll keep this issue open for now.

**Comment by liaujianjie** [comment]
> So I expect pg_net to hit 1.0 for next launch week tops.

This is very exciting news. I have the exact same use cases and concerns as as @psteinroe—we wish to make API calls to Segment and are worried about limits and failures.
