### ISSUE TITLE
Timeout was reached error with incorrect status: SUCCESS

### ISSUE THREAD

**Issue by tonyxiao** [supabase/pg_net#74]
# Bug report

1. Run supabase/postgres docker
2. Run sql
```sql
CREATE EXTENSION IF NOT EXISTS pg_net;
select
    net.http_post(
        url:='https://httpbin.org/post',
        body:='{"hello": "world"}'::jsonb
    );

select
  *
from
  net.http_collect_response(1);
```

@see

<a href="https://www.loom.com/share/57be14ed3bb541a889dfa2b0e0246f31">
    <p>pg_net: Timeout was reached - Watch Video</p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/57be14ed3bb541a889dfa2b0e0246f31-with-play.gif">
  </a>

Notice how the status says `SUCCESS`, but upon inspecting the `net._http_response` table, it says timeout was reached. Additionally it appears that the request was never made according to the remote server.

**Comment by steve-chavez** [comment]
Thanks for the report. Note that there's a timeout(by default 2 seconds) you can add to the function.

```sql
select
    net.http_post(
        url:='https://httpbin.org/post',
        body:='{"hello": "world"}'::jsonb,
        timeout_milliseconds := 5000
    );
```

The SUCCESS is indeed a mistake.

**Comment by tonyxiao** [comment]
I see. What's the default timeout on supabase itself? Or is it simply faster on supabase and therefore within the 2000ms timeframe?

**Comment by steve-chavez** [comment]
Default it's the same - 2 seconds. 

> Or is it simply faster on supabase and therefore within the 2000ms timeframe?

Yeah, latency might be lower due to network proximity.

**Comment by steve-chavez** [comment]
`http_collect_response` was made a private function on https://github.com/supabase/pg_net/pull/81.

For now it's better to inspect `net._http_response` directly. We're going to improve this on https://github.com/supabase/pg_net/issues/62.
