### ISSUE TITLE
Failed to toggle PG_NET: failed to create pg.extensions: function net.http_collect_response

### ISSUE THREAD

**Issue by logemann** [supabase/pg_net#82]
# Bug report

On disabling and re-enabling the extension PG_NET, i am getting:

**Failed to toggle PG_NET: failed to create pg.extensions: function net.http_collect_response(bigint, boolean) does not exist**

## Describe the bug

I paused and restored my supabase project (hosted) to get latest postgres and whatnot. Then i disabled PG_NET because i wanted to track down some issues i had with my migrations script.

I digged in deeper: The error is kind of crazy because PG_NET cant be installed because it expects a function which the extension itself should install.

The function is defined in: **pg_net/sql/pg_net--0.2--0.3.sql** but somehow my re-enablement doesnt run through this script again or the statement didnt run at all because the real error is in **pg_net--0.3--0.4.sql** on line 3:

`alter function net.http_collect_response(request_id bigint, async boolean) security definer;`

Funny enough that with 0.7, the function  was renamed to "_http_collect_response". 

## To Reproduce

Dont know if people can reproduce the bug. For me it was just disabling and re-enabling the extension after i did a pause/restore of the supabase project today.

## Expected behavior

i should be able to "enable" the Extension again.

## Screenshots

<img width="1018" alt="Bildschirm­foto 2023-02-03 um 01 10 05" src="https://user-images.githubusercontent.com/346353/216479343-31c4466c-f662-47ea-860c-85b6873677d3.png">

<img width="1500" alt="Bildschirm­foto 2023-02-03 um 00 35 16" src="https://user-images.githubusercontent.com/346353/216475036-f439d130-2279-458f-894c-51ca45fd3191.png">

## System information

Postgres: PostgreSQL 15.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit
Dont know where i can check the version of the supabase hosted image version or something.

## additional information
`select * from pg_available_extensions where name = 'pg_net';`
--> 0.7

I selected extensions as target schema. (default).
<img width="423" alt="Bildschirm­foto 2023-02-03 um 00 49 36" src="https://user-images.githubusercontent.com/346353/216476943-dd7549ec-3ff1-4ace-a0e0-1659b8282d6d.png">

**Comment by steve-chavez** [comment]
> because the real error is in pg_net--0.3--0.4.sql on line 3:
> alter function net.http_collect_response(request_id bigint, async boolean) security definer;

@logemann One question here, how do you know the error came from `pg_net--0.3--0.4.sql`? 

This could be misleading, the supabase dashboard also had the same instruction(`alter .. security definer`) but this was removed recently.

**Comment by logemann** [comment]
is this already live? Meaning, do i get 0.7.1 on pause/restore ?

**Comment by logemann** [comment]
@steve-chavez but its not merged into the current hosting image right? Just tested it.

**Comment by steve-chavez** [comment]
@logemann Yes, not yet. The https://github.com/supabase/postgres AMI needs to be pushed.

@pcnc Might have a timeframe.

**Comment by logemann** [comment]
@pcnc any timeframe for me? This is slowly getting critical.

**Comment by pcnc** [comment]
Hi @logemann - sorry for the delayed response.

We've pushed the Docker image earlier today (~16:00 GMT), and are going to release the platform AMI tomorrow in the morning Germany time - I'll ping you in this issue again to let you know when this is live.

Just a bit of extra info - free-tier projects need to be paused and resumed to update themselves to the latest image, pro-tier projects currently need to open a support ticket so we can operate this on behalf of users.

**Comment by logemann** [comment]
@pcnc thanks for letting me know. I just discovered on discord that i need to open a ticket for the AMI upgrade and also just requested it. I will make sure that support will wait another day to make the upgrade, otherwise i would be too early ;-)

**Comment by pcnc** [comment]
@logemann the AMI is now out, available on the platform.
We're working on making version information accessible to users, as well as providing self-serve upgrades, but right now the only place version information might be available in is dashboard API calls related to your project.

I've noticed your ticket and will follow up with you to schedule the upgrade.
