### ISSUE TITLE
Cannot enable pg_net extension

### ISSUE THREAD

**Issue by ntoombs19** [supabase/pg_net#84]
# Bug report

## Describe the bug

Enabling the pg_net extension either from SQL or from the studio results in the following error:
```
[42883] ERROR: function net.http_collect_response(bigint, boolean) does not exist Where: SQL statement "ALTER function net.http_collect_response(request_id bigint, async boolean) SECURITY DEFINER" PL/pgSQL function grant_pg_net_access() line 24 at SQL statement
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set up a Supabase DB
2. In the Studio, enable the extension PG_NET
3. See error

## Expected behavior

The PG_NET extension is enabled

## Screenshots

[Screenshot](https://share.cleanshot.com/VvG2zpsM)

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: 1.37.1
- Version of Node.js: v16.14.2

## Additional context

This issue can also be seen when enabling the extension from SQL
```
create extension pg_net;
```

**Comment by steve-chavez** [comment]
This was fixed on https://github.com/supabase/pg_net/issues/82, but it's still not pushed to production. Please subscribe to that issue :pray: .
