### ISSUE TITLE
Test Failures due to Timeout

### ISSUE THREAD

**Issue by TheOtherBrian1** [supabase/pg_net#94]
# Bug report

- [ X ] I confirm this is a bug with Supabase, not with my own application. 
- [ X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I noticed that my tests unexpectedly failed despite only making changes to the documentation. The root cause appears to be timeout errors resulting from the [httpbin](https://httpbin.org/) endpoints being excessively slow (over 2 seconds for response). These timeout errors are not accounted for in the tests, causing them to fail even with functional code.

## To Reproduce

To replicate, simply run the tests. A failure typically occurs due to the unanticipated timeout error.

## Expected behavior

The tests should retry requests if there is a timeout error.

**Comment by steve-chavez** [comment]
> The root cause appears to be timeout errors resulting from the [httpbin](https://httpbin.org/) endpoints being excessively slow (over 2 seconds for response).

@TheOtherBrian1 True, just noticed that as well. I think we should change those tests to use our Nginx server(one is started for the test suite) endpoints or Postman endpoints.

**Comment by TheOtherBrian1** [comment]
@steve-chavez I could modify the tests to work with the Postman Echo API. It's designed specifically for this kind of testing, and can be easily swapped with httpbin. Looking through the tests, it would probably only take me half an hour to an hour to implement. Timeouts are still bound to happen occasionally, but it would be an improvement.

**Comment by steve-chavez** [comment]
@TheOtherBrian1 Cool. Please go ahead.

**Comment by TheOtherBrian1** [comment]
@steve-chavez I added my changes to a [pull request](https://github.com/supabase/pg_net/pull/96), but it appears the tests are taking an unusually long amount of time (50 minutes at this point). By default Github actions will timeout after 6 hours, which seems excessive in this context. 

The [changes](https://github.com/supabase/pg_net/pull/96/files) I made were fairly mild, so I'm hesitant to think that I accidentally created an infinite loop that is holding up the server. It's possible that because the actions are dependent on the test code, the modifications interfered with their normal function. Either or, it is probably wise to lower the timeout limit.

**Comment by TheOtherBrian1** [comment]
@steve-chavez I have concerns regarding the [`test_http_requests_deleted_after_ttl`](https://github.com/supabase/pg_net/blob/master/test/test_http_requests_deleted_after_ttl.py) test function. It expects entries in the `net._http_response` table to be deleted after 5 seconds of being inserted. However, upon reviewing the [`worker.c`](https://github.com/supabase/pg_net/blob/8b55e96d0d4b194dd8896b6f2a0fa8ef525aa8b3/src/worker.c#L236) file, specifically lines [236](https://github.com/supabase/pg_net/blob/8b55e96d0d4b194dd8896b6f2a0fa8ef525aa8b3/src/worker.c#L236) and [39](https://github.com/supabase/pg_net/blob/8b55e96d0d4b194dd8896b6f2a0fa8ef525aa8b3/src/worker.c#L39), it seems that the deletion cycle has been adjusted to occur every 6 hours.

I may be misinterpreting the C code, but if my understanding is accurate, this test does not seem feasible and may need to be removed or commented out. You have a lot more insight on the inner workings of the extension than I do, so I would like to know your interpretation of this problem.
